[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "administrative-history"
version = "0.1.0"
description = "Toolkit for creating administrative history data model and using it to standardize and harmonize district-level socio-economic data."
authors = [
    { name="Jan Kiljański", email="jan.jozef.kiljanski@gmail.com" }
]
dependencies = [
    "geopandas",
    "matplotlib",
    "numpy",
    "pandas",
    "Pillow",
    "plotly",
    "Shapely",
    "streamlit"
]

[tool.setuptools.packages.find]
where = ["src"]