from __future__ import annotations

import os
from pathlib import Path
from typing import Union, Literal, Dict
import duckdb

from administrative_history.utils.helper_functions import read_economic_csv_input

class AdministrativeHistoryAPI:
    """
    AdministrativeHistoryAPI
    ========================

    This component serves as the **user-facing API** for accessing processed administrative
    history data through a DuckDB-backed analytical layer.

    It is constructed using an `AdministrativeHistoryProcessor` instance, which provides
    references to all processed Parquet outputs and metadata generated by the preprocessing
    pipeline. Instead of creating or modifying a `.duckdb` database file on disk,
    this version builds a **fully in-memory DuckDB instance** and exposes *views*
    directly over the Parquet files. Each process therefore operates in complete isolation
    — no file collisions, locks, or overwrites.

    **Purpose**
    -----------
    The API provides a convenient, consistent interface for querying harmonized or
    original administrative history datasets (cities, districts, regions, and associated
    metadata) without manual SQL management or file handling.

    **How it works**
    ----------------
    • On initialization, the class creates a private, in-memory DuckDB connection (`:memory:`).  
    • It automatically registers the Parquet datasets as **views** under the `adm` schema.  
    • Queries such as `load_data_table()` read directly from these Parquet sources using
      DuckDB’s vectorized query engine.  
    • The result is a lightweight analytical layer that is both **fast** and **stateless**,
      reflecting the current contents of the Parquet files each time the API is instantiated.

    **Advantages**
    --------------
    - ✅ **Zero collisions:** each API instance has its own DuckDB process and memory space  
    - ✅ **Always up-to-date:** automatically reflects the most recent Parquet outputs  
    - ✅ **No disk I/O overhead:** avoids creating or locking `.duckdb` files  
    - ✅ **Highly portable:** works anywhere DuckDB for Python is available  

    **Typical usage**
    -----------------
        # Load configuration and preprocessing setup
        config = load_adm_history_config("config.json")
        processing_config = load_processing_config("input/initial_region_state_list.json")

        # Construct the AdministrativeHistory and Processor
        adm_history = AdministrativeHistory(config, load_geometries=True)
        adm_history_processor = AdministrativeHistoryProcessor(processing_config, adm_history)

        # Initialize API (in-memory, collision-free)
        adm_history_api = AdministrativeHistoryAPI(adm_history_processor)

        # Load the needed data table
        population_1931, population_1931_metadata, population_1931_date = adm_history_api.load_data_table(
            data_table_id='1931-total_population',
            version='harmonized'
        )

    **Notes**
    ---------
    - Because the database exists only in memory, it is rebuilt from the Parquet views
      whenever a new instance is created.  
    - The in-memory mode is ideal for concurrent API servers or batch jobs that only
      need *read access*.  
    - If persistent or writable databases are required, a separate build step should
      create a physical `.duckdb` file that other processes open in `read_only=True` mode.
    """

    def __init__(self, adm_history_processor, overwrite_duckdb: bool = False):
        self.adm_history_processor = adm_history_processor
        self.adm_history = self.adm_history_processor.adm_history

        parquet_root = Path(self.adm_history_processor.processed_data_metadata_output_folder)
        if not parquet_root.exists():
            raise FileNotFoundError(
                f"Parquet folder not found at: {parquet_root}. "
                "This in-memory configuration requires Parquet inputs."
            )

        # One private, per-process connection
        self.con = duckdb.connect(database=':memory:', read_only=False)

        # Helpful performance toggles
        self.con.execute("PRAGMA threads = " + str(os.cpu_count() or 4))
        self.con.execute("PRAGMA enable_object_cache = true;")  # caches Parquet metadata & fragments

        self._register_views_over_parquet(parquet_root)

    def _register_views_over_parquet(self, root: Path):
        """Create schema + views that read Parquet directly (no materialization)."""
        mapping = {
            "city_datasets": root / "City_datasets.parquet",
            "district_datasets": root / "District_datasets.parquet",
            "region_datasets": root / "Region_datasets.parquet",
            "data_tables_metadata": root / "data_tables_metadata.parquet",
            "columns_metadata": root / "columns_metadata.parquet",
        }

        self.con.execute("CREATE SCHEMA IF NOT EXISTS adm;")

        # Helper to safely embed a Python string as a SQL string literal
        def sql_str(s: str) -> str:
            # Use forward slashes for cross-platform compatibility
            s = Path(s).as_posix()
            # Escape single quotes for SQL string literal
            return "'" + s.replace("'", "''") + "'"

        for table_name, parquet_path in mapping.items():
            p = os.fspath(parquet_path)
            if not Path(p).exists():
                raise FileNotFoundError(f"Missing Parquet for '{table_name}': {p}")

            # DDL + parameters is not allowed; embed the path as a literal
            self.con.execute(
                f"""
                CREATE OR REPLACE VIEW adm.{table_name} AS
                SELECT * FROM read_parquet({sql_str(p)}, union_by_name=true);
                """
            )

    def load_data_table(
        self,
        data_table_id: str,
        version: Union[Literal['original'], Literal['harmonized']],
        custom_grouping: Dict[str, str] = None,
        custom_grouping_method: Union[Literal['sum'], Literal['average']] = 'average'
    ):
        # ---- fetch metadata (unchanged) ----
        data_table_metadata_list = [
            data_table for data_table in self.adm_history_processor.processed_data_metadata.items
            if data_table.data_table_id == data_table_id
        ]
        if len(data_table_metadata_list) == 0:
            raise ValueError("No data table with the given id exists.")
        data_table_metadata = data_table_metadata_list[0]
        adm_level = data_table_metadata.adm_level

        if version == 'harmonized':
            adm_state_date = self.adm_history_processor.harmonize_to_date

            table_map = {
                'District': 'district_datasets',
                'Region': 'region_datasets',
                'City': 'city_datasets',
            }
            if adm_level not in table_map:
                raise ValueError(f"Unsupported adm_level in metadata: {adm_level}")

            base_view = f"adm.{table_map[adm_level]}"

            df_long = self.con.execute(
                f"""
                SELECT
                    {adm_level} AS unit,
                    variable_name,
                    value
                FROM {base_view}
                WHERE data_table_id = ?
                """,
                [data_table_id]
            ).df()

            if df_long.empty:
                raise ValueError(
                    f"No rows found in {base_view} for data_table_id='{data_table_id}'."
                )

            df = (
                df_long
                .pivot(index='unit', columns='variable_name', values='value')
                .sort_index()
            )
            df.index.name = adm_level

        else:
            # Original CSV path remains
            adm_state_date = data_table_metadata.orig_adm_state_date
            folder = self.adm_units_raw_data_folder
            path = os.path.join(folder, f"{data_table_id}.csv")
            df = read_economic_csv_input(adm_level=adm_level, input_csv_path=path)

            if adm_level not in df.columns:
                raise ValueError(f"'{adm_level}' column missing in data table: {data_table_id}")
            df.set_index(adm_level, inplace=True)

        # ---- rename according to metadata ----
        col_rename_dict = {
            col_name: data_table_metadata.columns[col_name].category["eng"]
            for col_name in df.columns
            if col_name in data_table_metadata.columns
        }
        if col_rename_dict:
            df.rename(columns=col_rename_dict, inplace=True)

        # ---- completeness check ----
        adm_state = self.adm_history.find_adm_state_by_date(adm_state_date)

        if adm_level == 'District':
            all_unit_names = adm_state.all_district_names(homeland_only=True)
        elif adm_level == 'Region':
            all_unit_names = adm_state.all_region_names(homeland_only=True)
        else:
            all_unit_names = None

        if adm_level in ['District', 'Region']:
            if set(all_unit_names) != set(df.index):
                missing_in_df = set(all_unit_names) - set(df.index)
                missing_in_adm_state = set(df.index) - set(all_unit_names)
                raise RuntimeError(
                    f"{adm_level} set for the loaded dataframe doesn't agree with the "
                    f"{adm_level.lower()} set for its adm. state!\n"
                    f"Missing in df: {missing_in_df}\n"
                    f"Missing in adm. state: {missing_in_adm_state}."
                )

            if custom_grouping:
                df = df.copy()
                df['__group__'] = df.index.map(custom_grouping)

                if df['__group__'].isnull().any():
                    missing_keys = df.index[df['__group__'].isnull()].tolist()
                    raise ValueError(f"Missing entries in custom_grouping for: {missing_keys}")

                grouped = df.groupby('__group__')
                if custom_grouping_method == 'sum':
                    df = grouped.sum(numeric_only=True)
                elif custom_grouping_method == 'average':
                    df = grouped.mean(numeric_only=True)
                else:
                    raise ValueError("custom_grouping_method must be either 'sum' or 'average'.")

                df.index.name = adm_level

        return df, data_table_metadata, adm_state_date
